export const links = [
  {
    id: 1,
    url: "/breakfast",
    link: "breakfast",
  },
  {
    id: 2,
    url: "/lunch",
    link: "lunch",
  },
  {
    id: 3,
    url: "/dinner",
    link: "dinner",
  },
];

export const foods = [
  {
    id: 1,
    price: "$32",
    name: "Green Goddess Chicken Salad",
    desc: "It is a non vegetarian salad which consists of the green goddess dressing mixed with chicken, peppers, olives and celery.",
    color: "#FF922C",
    bgColor: "#FFEEDE",
    url: "./assets/1.png",
  },
  {
    id: 2,
    price: "$35",
    name: "Asian Cucumber Salad",
    desc: "Asian Cucumber Salad Recipe made with crunchy cucumber, onion, rice wine vinegar, and a few secret ingredients!",
    color: "#54BF29",
    bgColor: "#99d681",
    url: "./assets/2.png",
  },
  {
    id: 3,
    price: "$37",
    name: "Roasted Vegetable Couscous",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    color: "#0B3948",
    bgColor: "#D9DBF1",
    url: "./assets/3.png",
  },
  {
    id: 4,
    price: "$34",
    name: "Parsley Salad",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    color: "#F11B44",
    bgColor: "#d47c8c",
    url: "./assets/4.png",
  },
  {
    id: 5,
    price: "$30",
    name: "Kale Salad With Toasted Pita",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    color: "#2CBCDC",
    bgColor: "#8fd8e9",
    url: "./assets/5.png",
  },

  {
    id: 6,
    price: "$32",
    name: "Spinach and Orzo Salad",
    desc: "It is a non vegetarian salad which consists of the green goddess dressing mixed with chicken, peppers, olives and celery.",
    color: "#FF922C",
    bgColor: "#FFEEDE",
    url: "./assets/6.png",
  },
  {
    id: 7,
    price: "$35",
    name: "Slow-Cooker Chicken",
    desc: "Asian Cucumber Salad Recipe made with crunchy cucumber, onion, rice wine vinegar, and a few secret ingredients!",
    color: "#54BF29",
    bgColor: "#99d681",
    url: "./assets/7.png",
  },
  {
    id: 8,
    price: "$36",
    name: "Torn Cabbage Salad",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    color: "#0B3948",
    bgColor: "#D9DBF1",
    url: "./assets/8.png",
  },
  {
    id: 9,
    price: "$31",
    name: "Raw Spiralized Zucchini Noodles",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    color: "#2CBCDC",
    bgColor: "#8fd8e9",
    url: "./assets/9.png",
  },
  {
    id: 10,
    price: "$35",
    name: "Chilled Zucchini and Orzo Salad",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    color: "#F11B44",
    bgColor: "#d47c8c",
    url: "./assets/10.png",
  },
];
